CHANGELOG.md
STAC-extensions.yaml
extensions/context/README.md
extensions/context/context.fragment.yaml
extensions/context/examples/example.json
extensions/context/json-schema/schema.json
package-lock.json

1. Remove the non-existent "next" parameter as required in the yaml spec
2. Reorder properties so they're always in order "returned, limit, matched"

cleanup Context Extension text

---

.circleci/rc.yaml

**Related Issue(s):** None
The CI rule removed misbehaves a bit and is not so important. Removed in STAC spec so removed here too for consistency.

Remove a misbehaving CI rule

---

CHANGELOG.md
api-spec.md

n/a
1. require root link for search be `application/geo+json`, which matches the response type of the /search endpoint

specify type of search Link, wordsmith other API text

---

CHANGELOG.md
api-spec.md

**Related Issue(s):** #44
1. Update api-spec.md Returns value to match that of OAFeat spec
I implemented this wrong about a year ago, and just realized that this is where I got that incorrect idea from. 
Also, https://earth-search.aws.element84.com/v0/collections implements this as a top-level array instead of the OAFeat defintion @matthewhanson 

Fix collection description

---

README.md
api-spec.md
principles.md

**Related Issue(s):** #1
1. Updates of links

link clean-up

---

api-spec.md

**Related Issue(s):** #2 
1. Removed the language around paging being an extension (hopefully fully, I couldn't find it in the openapi doc)
- [n/a] API only: I have run `npm run generate-all` to update the [generated OpenAPI files](https://github.com/radiantearth/stac-api-spec/blob/dev/README.md#openapi-definitions).

Paging no longer an extension #20

---

CHANGELOG.md
STAC-extensions.yaml
STAC.yaml
api-spec.md
openapi/OAFeat.yaml
openapi/STAC.yaml

**Related Issue(s):** #28 #47 
1. Update the openapi yaml to only allow 4 or 6 element bbox arrays
2. Link to examples and put in a bit more language around bbox

Bbox improvements

---

.remarkignore
CHANGELOG.md
README.md
api-spec.md
extensions/README.md
extensions/context/README.md
package.json

**Related Issue(s):** #55
1. Set STAC Spec version from 0.9.0 to 1.0.0-beta.2

Set stac-spec to 1.0.0-beta.2 #55

---

.circleci/config.yml
CHANGELOG.md
STAC-extensions.yaml
STAC.yaml
extensions/transaction/transaction.fragment.yaml
extensions/version/version.fragment.yaml
openapi/OAFeat.yaml
openapi/STAC.yaml

**Related Issue(s):** #8, #10
*Changes based on #10, so need to merge that first.*

Fixes and CI for OpenAPI files 

---

STAC-extensions.yaml
STAC.yaml
openapi/OAFeat.yaml
openapi/STAC.yaml

**Related Issue(s):** https://github.com/opengeospatial/ogcapi-features/issues/454
1. Remove bbox-crs for now, it's only defined in the Features CRS extension and seems to confuse users.

Remove bbox-crs for now

---

CHANGELOG.md
README.md
api-spec.md

**Related Issue(s):** #42 
1. Added an intro to ease people in a bit more gently
2. added paragraph on the compliance requirements, as requested in #42

Minor clean-up and more intro

---

CHANGELOG.md
PROCESS.md
README.md
api-spec.md

**Related Issue(s):** #55 
1. Add note about properly checking out submodules
2. Update stac-spec links to be relative
3. Make clear the features API dependency
4. Added a PROCESS.md to have a place to put reminders for release.
5. Add what updates are needed for a 'release' (update submodule). Ended up making it so you don't need to update
the stac-spec version - just instructed people to check the CHANGELOG of the submodule to see.

Updates for relative links and being clear on version dependencies

---

CHANGELOG.md

#63 
1. remove extra characters preventing the markdown tags from working

fix errant slashes in CHANGELOG, resolves #63

---

CHANGELOG.md
STAC-extensions.yaml
extensions/transaction/README.md
extensions/transaction/transaction.fragment.yaml

updated to make clear the relationship with ogc api - features simple transactions extension
**Related Issue(s):** #33 
1. Put in links to OGC API - Features Part 4: Simple Transactions extension, and made clear that STAC's extends. Thankfully
the semantics seemed to all be the same, but we should check to be sure when they have an openapi sample document
- [n/a] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).

Align with OGC API - Features Part 4: Simple Transactions extension

---

README.md
item-search/README.md

1. Added language to make it clearer how to indicate POST can be used.

Item search POST clarification

---

CHANGELOG.md
core/commons.yaml
core/openapi.yaml
ogcapi-features/openapi.yaml

**Related Issue(s):** #74
1. Add conformance classes to landing page in OpenAPI

Add conformance classes to landing page #74

---

core/openapi.yaml
ogcapi-features/openapi.yaml

**Related Issue(s):** https://github.com/radiantearth/stac-api-spec/pull/87#issuecomment-741927717
1. Quick fix to include conformsTo on OAFeat landing page

Show conformsTo on landing page of OAFeat

---

overview.md

1. Edit details on conformance, from Josh's review on gitter.

Clarity on conformance

---

.circleci/rc.yaml
CHANGELOG.md
README.md
core/commons.yaml

- https://github.com/radiantearth/stac-spec/issues/1064
- https://github.com/opengeospatial/ogcapi-features/pull/520
1. Adopt clarification by OGC API - Features on multiple extents in collections
cc @cportele

Clarification on multiple bounding boxes in an extent

---

CHANGELOG.md
item-search/README.md
item-search/openapi.yaml

**Related Issue(s):** #124 
1. Don't deactivate other query params when `ids` is passed to item search

Don't deactivate other search parameters when filtering with ids

---

CHANGELOG.md
README.md
implementation.md
overview.md

**Related Issue(s):** #99
1. Add recommendation to enable CORS for public APIs

Add CORS recommendation

---

item-search/README.md

**Related Issue(s):** NA
1. 
2. 

typo; escaping * in MD; stac_version in ItemCollection; fixing reference

---

.circleci/rc.yaml
fragments/filter/openapi.yaml

1. fix minor issues with liniting

Linting fixes

---

CHANGELOG.md
extensions.md
fragments/query/README.md
item-search/README.md

**Related Issue(s):** None
1. Change deprecated description
2. Query extension as scheduled to be deprecated

Change deprecated descrition; query ext as sch to be deprecated

---

CHANGELOG.md
core/commons.yaml
fragments/filter/README.md
fragments/itemcollection/README.md
fragments/itemcollection/examples/itemcollection-sample-full.json
fragments/itemcollection/examples/itemcollection-sample-minimal.json
fragments/itemcollection/openapi.yaml

**Related Issue(s):** #141
1. remove ItemCollection fields stac_version and stac_extensions, as they are not STAC entities

Remove stac version and extensions from item collection

---

item-search/README.md

**Related Issue(s):** #164 
1. clarify bbox parameter formatting

add clarifying statement about bbox parameter formatting

---

.circleci/rc.yaml
extensions.md

**Related Issue(s):** #155
1. reorganize table of extensions into list to avoid HTML and long lines

reorganize extensions list to avoid long lines and html

---

implementation.md
item-search/README.md

**Related Issue(s):** #146
1. provide additional details about implementing the datetime parameter beyond what is provided in OAFeat.

add detailed description of datetime parameter use

---

CHANGELOG.md
fragments/filter/README.md

**Related Issue(s):** #158
Refactors Filter Extension conformance classes to more closely align with OGC API Part 3 changes coming soon. 
The current draft Simple CQL class is definitely going away (https://github.com/opengeospatial/ogcapi-features/issues/579#issuecomment-874131446), but I don't think the proposed new ones meet the needs of STAC API either 🤷🏻 I think we're going to need to keep our own that don't align with the OAF ones, but hopefully they'll align eventually.  Since Part 3 is a work in progress, having our own conformance classes will help insulate us from those changes and allow us to move forward without waiting for those to be finalized.

change: refactor Filter Extension conformance classes

---

item-search/README.md

**Related Issue(s):** #160 
1. clarify 3d bbox query over Item with 2d bbox means Item is at elevation 0

clarify 3d bbox query over 2d geometry

---

core/README.md
item-search/README.md
ogcapi-features/README.md

**Related Issue(s):** #142
1. Add table with Link Relations to each conformance class to clarify which ones should be implemented.

add link relation table to each conformance class

---

fragments/filter/openapi.yaml

**Related Issue(s):** #156
1. fix queryables definition in Filter to at least have a content type and object. In the future, we should have a precise definition for JSON Schema, but this is quite a bit of work to write. 

fix filter queryables definition to at least have a content type and object

---

.circleci/build-openapi.sh
.circleci/config.yml
build/index.html
build/swagger-config.yaml
core/README.md
fragments/filter/README.md
implementation.md
item-search/README.md
package.json

**Related Issue(s):** #165
1. change redoc build to use openapi-cli instead of swagger-cli, which should fix the issue with the published version of 
2. replace index.html with current recommended content from ReDoc
2. cleanup redoc warnings

fix redoc build and cleanup warnings

---

ogcapi-features/README.md
overview.md

**Related Issue(s):** #161
1. Add clarifying language about using link relation `items` instead of `item` 

add clarifying language about using items instead of item

---

fragments/filter/README.md

**Related Issue(s):** #186
1. fix language around support for CQL

fix text around cql support

---

CHANGELOG.md
collections/README.md
collections/openapi.yaml
core/openapi.yaml
item-search/openapi.yaml
overview.md

**Related Issue(s):** #134
1. Add Collections conformance class defintion

add collections api definition

---

CHANGELOG.md
README.md
build/swagger-config.yaml
collections/README.md
collections/openapi.yaml
core/README.md
core/commons.yaml
core/openapi.yaml
extensions.md
fragments/context/README.md
fragments/context/openapi.yaml
fragments/fields/README.md
fragments/fields/openapi.yaml
fragments/filter/README.md
fragments/filter/openapi.yaml
fragments/itemcollection/openapi.yaml
fragments/query/README.md
fragments/query/openapi.yaml
fragments/sort/README.md
fragments/sort/openapi.yaml
item-search/README.md
item-search/openapi.yaml
ogcapi-features/README.md
ogcapi-features/extensions/transaction/README.md
ogcapi-features/extensions/transaction/openapi.yaml
ogcapi-features/extensions/version/README.md
ogcapi-features/extensions/version/openapi.yaml
ogcapi-features/openapi.yaml
overview.md
package.json

1. update version from 1.0.0-beta.2 to 1.0.0-beta.3

update version from 1.0.0-beta.2 to 1.0.0-beta.3

---

CHANGELOG.md
fragments/filter/README.md

**Related Issue(s):** none
1. Filter Extension conformance class Queryable First Operand is mistakenly named, as this class actually allows the **second** operand to be queryable. Renamed appropriately. 

rename Queryable First Operand to Queryable Second Operand

---

README.md
build/swagger-config.yaml
collections/README.md
collections/openapi.yaml
core/README.md
core/commons.yaml
core/openapi.yaml
extensions.md
fragments/context/README.md
fragments/context/openapi.yaml
fragments/fields/README.md
fragments/fields/openapi.yaml
fragments/filter/README.md
fragments/filter/openapi.yaml
fragments/itemcollection/openapi.yaml
fragments/query/README.md
fragments/query/openapi.yaml
fragments/sort/README.md
fragments/sort/openapi.yaml
item-search/README.md
item-search/openapi.yaml
ogcapi-features/README.md
ogcapi-features/extensions/transaction/README.md
ogcapi-features/extensions/transaction/openapi.yaml
ogcapi-features/extensions/version/README.md
ogcapi-features/extensions/version/openapi.yaml
ogcapi-features/openapi.yaml
overview.md
package.json

1. Update version references to 1.0.0-beta.4, since we know what the next version is going to be. 

update version references to 1.0.0-beta.4

---

collections/README.md
core/README.md
fragments/filter/README.md
item-search/README.md
ogcapi-features/README.md
ogcapi-features/extensions/version/README.md
overview.md

**Related Issue(s):** #206
[question on gitter.im](https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=612fa59c8065e87a8ebd2659)
1. Add missing `"type": "Catalog"`, `"type": "Collection"` or  `"type": "Feature"` for some examples when it was lacking

Missing types

---

CHANGELOG.md
collections/README.md
core/README.md
extensions.md
item-search/README.md
ogcapi-features/README.md

…implemented for each conformance class
**Related Issue(s):** #195 
1. change wording of required endpoints for each conformance class from "should" to "shall".
Technically this is a breaking change, but it was understood before that these were required, we just used the wrong word in the spec.

Shall and endpoint table

---

CHANGELOG.md
extensions.md
fragments/context/README.md
fragments/fields/README.md
fragments/sort/README.md
ogcapi-features/README.md

**Related Issue(s):** #136
1. support binding sort, fields, and context extension to STAC Features

support binding sort, fields, and context extension to STAC Features

---

CHANGELOG.md
collections/README.md
core/README.md
fragments/fields/README.md
fragments/filter/README.md
fragments/itemcollection/README.md
fragments/sort/README.md
implementation.md
item-search/README.md
ogcapi-features/README.md
ogcapi-features/extensions/version/README.md

incorporate feedback on collections from beta.3, cleanup related text in other components
**Related Issue(s):** #195
1. incorporate feedback from @m-mohr on collections
2. fix more instances of should vs. shall/must

incorporate feedback on collections from beta.3, cleanup related text

---

core/commons.yaml

**Related Issue(s):** #224 
1. remove stray mention of bbox-crs in commons openapi defintion description text

224 remove bbox crs

---

CHANGELOG.md
fragments/filter/README.md

1. Several Filter Extension Interval and Timestamp examples are incorrect wrt to the latest CQL spec

Fix filter ex interval and timestamp examples

---

CHANGELOG.md
browseable/README.md
children/README.md
collections/README.md
core/README.md

merge (again) for 1.0.0-beta.5
This includes mostly formatting changes to remove the stray space at the end of lines, fixes a few of the CQL2 examples, and updates the newer conformance classes to be Proposal instead of Pilot.

dev -> master merge for 1.0.0-beta.5 (second attempt)

---

browseable/README.md
children/README.md
collections/README.md
core/README.md
fragments/filter/README.md
fragments/itemcollection/examples/itemcollection-sample-full.json
item-search/README.md
item-search/examples.md
ogcapi-features/README.md
overview.md

- #244 
1. make all example URLs consistent at stac-api.example.com

Update example urls

---

item-search/README.md
item-search/examples.md
ogcapi-features/README.md

**Related Issue(s):** #256
1. add type=application/geo+json to prev and next link relations

add type=application/geo+json to prev and next links

---

item-search/README.md

**Related Issue(s):**
- #255
1. update language around search link rel

clarify wording of search link rel requirement

---

CHANGELOG.md
browseable/README.md
children/README.md
collections/README.md
core/README.md
item-search/README.md
item-search/openapi.yaml
ogcapi-features/README.md
ogcapi-features/extensions/transaction/openapi.yaml
ogcapi-features/openapi.yaml
overview.md

- https://github.com/radiantearth/stac-api-spec/issues/274
- https://github.com/radiantearth/stac-api-spec/issues/272
1. change all uses of "shall" to "must". semantics do not change. 
2. stylize all non-linked conformance class names. (previously a mix of unstylized and use of code style)

change all uses of shall to must, and stylize all non-linked conformance classes

---

fragments/filter/README.md

remove stray text from Filter

---

README.md
build/index.html

1. Add Releases list to Readme to make it more clear where to find specific versions of STAC when we move to only having a main branch
2. Add all the conformance classes to the build index

Add Releases to readme and add all conformance classes to build index

---

children/openapi.yaml
collections/openapi.yaml
core/commons.yaml
core/openapi.yaml
ogcapi-features/openapi.yaml
package-lock.json

1. remove unused openapi response codes
2. fix several stac_version values

remove unused openapi spec elements and fix several stac_version values

---

fragments/filter/openapi.yaml

See https://github.com/opengeospatial/ogcapi-features/commit/c1c580116398a8b6c6cd4acb43863ae7461126d3.
- #301
1. Use `booleanExpression` instead of `booleanValueExpression`

Update ref to use booleanExpression

---

ogcapi-features/README.md

1. Update example link type to be `application/json` instead of `application/geo+json` for collections list.

Collections list is just plain JSON

---

.circleci/config.yml
.github/pull_request_template.md
CONTRIBUTING.md
README.md
extensions.md

- #259
Change branch strategy to use main w/ tags instead of dev/master. 
Former PR here: https://github.com/radiantearth/stac-api-spec/pull/268
There are two aspects to this change:
1. **Changing from using a develop->released branch model to a single branch** -- Until now, the `dev` branch was a rapidly-changing work-in-progress. It made sense to not make this the first thing people saw when they came to this repo. As we converge towards 1.0.0, there will be fewer significant changes in main that are not part of the latest released version. Most repos don't have master or a branch with their latest released version as the default branch, so users are used to `main` being the development tip.
2. **Changing the name of the primary branch from …

Use main instead of to dev/master

---

ogcapi-features/README.md

It looks like the conformance classes were copy/pasted from item search, but instead they should contain ogcapi-features.

Fix conformance classes

---

children/README.md

This suggests a few minor changes to the examples in the STAC API - Children readme.
1. Remove trailing commas from JSON examples
2. Remove extent from catalog (to make it clearer that it is just a catalog and not a collection)
3. Make one of the children a collection (since it already had the required fields)

Updated examples for children

---

fragments/filter/README.md

- #299 
1. Fix Filter Extension example for isNull that was missing array brackets around args value 

fix filter extension is null example

---

ogcapi-features/extensions/transaction/README.md

- #292
1. update wording in transaction extension

update wording in transaction extension

---

.github/pull_request_template.md

- n/a
1.  update pr template to reference main instead of dev

update pr template to reference main instead of dev

---

.remarkignore
CODE_OF_CONDUCT.md

- #263 
1. Update code of conduct to version 2.1

update code of conduct to 2.1

---

CHANGELOG.md
item-search/README.md

- #334
1. limit semantics now match OAFeat. The limit parameter must be less than the maximum value advertised in the service description and the server must not return more items than the limit parameter. 

revise limit semantics

---

item-search/README.md

Invalid JSON example in README

---

implementation.md
item-search/README.md
item-search/examples.md
ogcapi-features/README.md
package-lock.json
package.json
stac-spec/.circleci/rc.yaml

- n/a
1. fix code samples using the http type to use none, since none of these were http format, they showed red highlights in GH

fix code samples using the http type to use none

---

.circleci/publish.js
stac-spec/.circleci/publish-schemas.js

- n/a
1. When renaming the default branch from dev to main, I missed these two uses of dev in the schema publishing scripts. Fixing that.

fix publishing schemas by renaming default from dev to main

---

CITATION.cff

**Related Issue(s):** None, but https://github.com/radiantearth/stac-spec/pull/1188
Also add citation information to the API spec, similarly to the stac spec, but adapted to the API repo etc.
Each release we need to update the version numbers and the release date in this file! @philvarner May need slight changes for the RC2 release.

Add citation information for the API spec

---

CHANGELOG.md
README.md
build/swagger-config.yaml
core/README.md
core/commons.yaml
core/openapi.yaml
fragments/itemcollection/openapi.yaml
item-search/README.md
item-search/openapi.yaml
ogcapi-features/README.md
ogcapi-features/openapi-collections.yaml
ogcapi-features/openapi-features.yaml
overview.md
package-lock.json
package.json

- n/a
1. Release 1.0.0-rc.2 
<https://github.com/radiantearth/stac-api-spec/compare/v1.0.0-rc.1..main>
- Added optional `numberMatched` and `numberReturned` fields to ItemCollection to align with OGC Commons
and OAFeat.
- The Collections specification has been incorporated into the *Features* specification, but remains as
a separate conformance class. 
- The Browseable specification has been incorporated into the *Core* specification, but remains as
a separate conformance class.
- Extensions moved to standalone specification repositories:
- [Items and Collections API Version](https://github.com/stac-api-extensions/version) 
- [Fields](https://github.com/stac-api-extensions/fields)
- [Filter](https://github.com/stac-api-extensions/filter)
- …

1.0.0-rc.2 release

---

core/README.md
implementation.md

N/A
1. Remove repeated "the"
- I confirmed there are no repeated "the" anymore by searching "the the" in this repository.

Fix typos (repeated "the")

---

item-search/examples.md

N/A
1. Fix invalid JSON in `item-search/examples.md`
- https://github.com/radiantearth/stac-api-spec/pull/264 removed `"href"` key

Fix invalid JSON in item-search/examples.md

---

core/README.md

**Related Issue(s):**  None
1. Remove trailing commas in JSON as they are usually invalid

Remove trailing commas in JSON example

---

.circleci/build-openapi.sh

- https://github.com/radiantearth/stac-api-spec/issues/356
1. Fix conformance class schema publishing

fix conformance class publishing

---

README.md
extensions.md

- https://github.com/radiantearth/stac-api-spec/issues/372
1. Remove the extensions table as they are now at https://stac-api-extensions.github.io

move extensions to https://stac-api-extensions.github.io

---

core/README.md
item-search/README.md
ogcapi-features/README.md

- n/a
1. Add headers to readmes so VS Code markdown-all-in-one won't remove Summary content

fix headers so VSCode header won't remove Summary section

---

core/commons.yaml

- n/a
1. fix `/conformances` -> `/conformance`

in openapi, fix name of /conformance endpoint (was /conformances)

---

README.md
core/README.md
fragments/itemcollection/README.md
item-search/README.md
ogcapi-features/README.md
overview.md

- n/a
1. link to STAC API Extensions site instead of listing them

link to STAC API Extensions site instead of listing them

---

CHANGELOG.md
core/openapi.yaml
item-search/openapi.yaml
ogcapi-features/openapi-collections.yaml
ogcapi-features/openapi-features.yaml

- https://github.com/radiantearth/stac-api-spec/issues/361
1. Add x-conformance-classes extension in openapi schemas

add openapi extension x-conformance-classes

---

CHANGELOG.md
fragments/itemcollection/examples/itemcollection-sample-full.json
item-search/README.md
item-search/examples.md

- https://github.com/radiantearth/stac-api-spec/issues/340
1. Add `root` as a required link rel on the Item Search response ItemCollection

add "root" link rel as required for item search response

---

core/commons.yaml

- https://github.com/radiantearth/stac-browser/issues/253
- https://github.com/radiantearth/stac-api-spec/issues/388
1. Explicit mention of the type values, otherwise Catalogs could be Collections and Collections could be Catalogs with additional Collection fields.

Add explicit type restrictions

---

CHANGELOG.md
core/README.md
overview.md

- https://github.com/radiantearth/stac-api-spec/issues/392
1. Remove Browseable text, moved to https://github.com/stac-api-extensions/browseable

remove browseable, moved to https://github.com/stac-api-extensions/browseable

---

core/openapi.yaml

- #403 
1. remove mention of data link rel from core spec, since it's defined in Collections and Features rather than Core

remove from core openapi mention of 'data' link rel, which is in a different spec & conformance class

---

CHANGELOG.md
ogcapi-features/README.md

- [#362](https://github.com/radiantearth/stac-api-spec/issues/362#issuecomment-1457397588)
1. Use the `collection` relation type for links from an item to a collection
The STAC Collection spec includes [this language](https://github.com/radiantearth/stac-spec/blob/v1.0.0/collection-spec/collection-spec.md#relation-types):
> it is REQUIRED that Items linked from a Collection MUST refer back to its Collection with the collection relation type
This proposed change makes the STAC API spec consistent with that requirement.

Use collection relation for links to collection

---

CHANGELOG.md
core/README.md
item-search/README.md
ogcapi-features/README.md

- https://github.com/radiantearth/stac-api-spec/issues/413
1. Link `type` field is no longer required, after a clarification in the OAFeat spec about that as a (mistaken) requirement 

link type no longer required

---

CHANGELOG.md
CITATION.cff
README.md
core/README.md
core/commons.yaml
core/openapi.yaml
fragments/itemcollection/openapi.yaml
item-search/README.md
item-search/openapi.yaml
ogcapi-features/README.md
ogcapi-features/openapi-collections.yaml
ogcapi-features/openapi-features.yaml
overview.md
package-lock.json
package.json

- n/a
1. release prep for 1.0.0-rc.4

release prep 1.0.0-rc.4

---

item-search/README.md

The bbox in the example has xmin > xmax.

Fix bbox in README example

---

CHANGELOG.md
core/commons.yaml

1. Added the missing `assets` property to Collections

Added the missing `assets` property to Collections

---

item-search/examples.md

added 'last page' response example
- #
1. 
2. 

Update examples.md to include 'last page' response example
