api-spec.md
**Related Issue(s):** None
Fixing two minor issues found in the last STAC meeting (broken table, incorrect Data Type for /collections)
=> Fixing two minor issues found in the last STAC meeting

.github/pull_request_template.md, CHANGELOG.md, CODE_OF_CONDUCT.md, LICENSE
**Related Issue(s):** #13, #18
Added missing documents
=> Added CHANGELOG #13

examples.md
1. Minor updates to examples
2. 
=> updates to examples to be a bit more clear

package.json
**Related Issue(s):** None
1. Update dependencies to make sure everyone is on the same page - will hopefully fix some build errors
=> Update dependencies to make sure everyone is on the same page

README.md
1. Remove line break, looks strange
=> Remove line break

README.md
1. Added that we use semver, just like STAC-spec
2. 
=> Note in readme on SemVer

item-search/README.md
1. removed the 'geometry filtering' thing as it was confusing, replaced with actual filter capabilities.
=> Clarification of extension capabilities

CHANGELOG.md
Added heading in changelog for 1.0.0-beta.1
=> Update for 1.0.0-beta.1 release

CHANGELOG.md, core/README.md, item-search/README.md, ogcapi-features/README.md
**Related Issue(s):** #104 
1. Update dev with changes on master
=> Update dev with changes on master

README.md, core/README.md, item-search/README.md, ogcapi-features/README.md
**Related Issue(s):** #113
1. add ToC to all pages
2. add text about how Item Search is limited and most behavior will be defined in extensions
=> Readme item search reorg

extensions.md
1.  Add third-party extension to the extensions table
=> add third-party extension

v1.0.0-beta.2/ogcapi-features/extensions/transaction/index.html, v1.0.0-beta.2/ogcapi-features/extensions/transaction/openapi.yaml, v1.0.0-beta.2/ogcapi-features/extensions/version/index.html, v1.0.0-beta.2/ogcapi-features/extensions/version/openapi.yaml, v1.0.0-beta.2/ogcapi-features/index.html, v1.0.0-beta.2/ogcapi-features/openapi.yaml
**Related Issue(s):** #165
1. manual fix for the page https://api.stacspec.org/v1.0.0-beta.2/ogcapi-features/
This is automatically built from circleci when a tag is created. I can't figure out how to get this to publish locally from master, so this is just adding the files manually.
2. The CircleCI build error is b/c this branch doesn't have a circleci build config, because it doesn't need one.
3. I spot-checked several of the changes in the openapi configs, and they equivalent code -- in most cases, they're a change from definitions being inline to being referenced.
=> fix for v1.0.0-beta.2 ogcapi-features

implementation.md
**Related Issue(s):** #103
1. add text about globally unique tuples
=> Add text about Globally unique ids

extensions.md
n/a
1. fix markdown linting issue
=> fix markdown linting issue

fragments/itemcollection/README.md, package-lock.json
- #315 
1. defintion of ItemCollection features and links were missing array brackets
=> fix ItemCollection definition of features and links that was missing array brackets

item-search/README.md, ogcapi-features/README.md
Ref: https://github.com/radiantearth/stac-api-spec/pull/321#discussion_r958556439
- #
1. 
2. 
=> Fix broken links

core/README.md
- N/A
1. Fix a typo in a string in an example JSON document
=> Fix a typo in an example

overview.md
- #359 
1. Revisions to overview document to more closely align with language we currently use
=> revise overview page

CHANGELOG.md, CITATION.cff, README.md, core/README.md, core/commons.yaml, core/openapi.yaml, fragments/itemcollection/openapi.yaml, item-search/README.md, item-search/openapi.yaml, ogcapi-features/README.md, ogcapi-features/openapi-collections.yaml, ogcapi-features/openapi-features.yaml, overview.md, package-lock.json, package.json
- n/a
1. Preparations for 1.0.0-rc.3 release
=> prep for 1.0.0-rc.3 release

CHANGELOG.md, CITATION.cff, README.md, core/README.md, core/commons.yaml, core/openapi.yaml, fragments/itemcollection/openapi.yaml, item-search/README.md, item-search/openapi.yaml, ogcapi-features/README.md, ogcapi-features/openapi-collections.yaml, ogcapi-features/openapi-features.yaml, overview.md, package-lock.json, package.json
- n/a
1. release prep for 1.0.0
=> release prep for 1.0.0

CHANGELOG.md, core/commons.yaml
1. Change min/max to minimum/maximum
2. Allow JSON Schema
3. Align with JSON Schema from stac-spec
=> Summaries were not up to date

item-search/README.md
added sentence about how to handle first/last pages by omitting the corresponding link relations in the result.
- #
1. 
2. 
=> Update README.md to include sentence of how clients shall interpret last page

CHANGELOG.md, fragments/collectioncollection/README.md, fragments/collectioncollection/examples/sample-full.json, fragments/collectioncollection/examples/sample-minimal.json, fragments/collectioncollection/openapi.yaml, ogcapi-features/openapi-collections.yaml
- #442 
- #447 
1. Added fragment for CollectionCollection
2. Add numberMatched, numberReturned fields
cc @emmanuelmathot 
=> Add CollectionCollection
